server:
  port: 9093

spring:
  application:
    name: sleuth-zipkin
  zipkin:
    baseUrl: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
